version: '3.6'

services:
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - "API_URL=http://localhost:8080/v2/api-docs"
    ports:
      - "3200:8080"
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jet
    ports:
      - "5431:5432"
    networks:
      - backend_net
    volumes:
      - $HOME/pgdata-trade:/var/lib/postgresql/data

networks:
  backend_net:
    driver: bridge

